### ISSUE TITLE
Пара вопросов

### ISSUE THREAD

**Issue by provank** [nkrkv/pyinsales#13]
Можно пример  «product_data» для add_product(self, product_data):
И как получить значение текущего API-Usage-Limit ?  
Спасибо!

**Comment by nkrkv** [comment]
Вот минимальный пример создания продукта:

```py
        result = api.add_product({
            'category_id': 123456,
            'title': 'Тапки',
            'variants-attributes': [{
                'sku': '963258741',
                'price': Decimal(100),
            }]
        })

        product_id = result['id']
        variant_id = result['variants'][0]['id']
```

Другие поля см. в документации http://api.insales.ru/#product-create-product-xml

По поводу Usage Limit: оно не предоставляется наружу методами pyinsales

**Comment by provank** [comment]
Получается счет API-Usage-Limit идет, но узнать текущий никак?

**Comment by nkrkv** [comment]
Через pyinsales никак.

Можете в конструктор передать аргументы `retry_on_xxxx`, тогда при исчерпании квоты `pyinsales` подождёт, пока она не появится снова и начнёт с того же места.
