### ISSUE TITLE
Пояснение к созданию товаров

### ISSUE THREAD

**Issue by KAHTEC** [nkrkv/pyinsales#3]
Не получается создать заказ. Подскажите, что я делаю не так?

product_data = {
 'archived': False,
 'available': True,
 'canonical-url-collection-id': 4331020,
 'category-id': 6942456,
 'currency-code': 'RUR',
 'description': 'test description',
 'html-title': None,
 'ignore-discounts': None,
 'is-hidden': False,
 'meta-description': None,
 'meta-keywords': None,
 'option-names': [],
 'short-description': 'Test short short-description',
 'sort-weight': None,
 'title': 'test item title',
 'unit': 'pce',
 'variants': [{'available': True,
   'barcode': None,
   'base-price': Decimal('6200.0'),
   'base-price-in-site-currency': Decimal('6200.0'),
   'cost-price': Decimal('4200.0'),
   'cost-price-in-site-currency': Decimal('4200.0'),
   'old-price': None,
   'old-price-in-site-currency': None,
   'option-values': [],
   'price': Decimal('6200.0'),
   'price-in-site-currency': Decimal('6200.0'),
   'price2': None,
   'price2-in-site-currency': None,
   'quantity': None,
   'sku': 'ART-111',
   'title': None,
   'weight': Decimal('0.1')}],
 'vat': -1
}

api.add_product(product_data)

В ответ приходит ошибка:
 POST request to /admin/products.xml returned: 422
b'<?xml version="1.0" encoding="UTF-8"?> Нельзя создавать товар без модификаций</error>
</errors>

**Comment by nkrkv** [comment]
Это вопрос к работе API InSales, не к pyinsales. Попробуйте добиться работоспособности запросов из CURL, а затем переходите к pyinsales. Я заметил, что у вас в запросе вместо поля `variants-attributes` поле `variants`. Вы пытаетесь взять результат GET-запроса к товару и положить его в качестве нового. Так не получится, увы. За поддержкой по работе самого API рекомендую писать в InSales.
